services:
  - type: web
    name: catchball-seattle
    runtime: node
    buildCommand: |
      cd frontend && npm ci && npm run build &&
      cd ../backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
